### PR TITLE
Fixed compile broken by commit ae98dfafa9

### PR DESCRIPTION
**Pull request by taktoa**
Unless I'm mistaken, this should fix the purescript-native build (or maybe it isn't really broken and I'm just doing something wrong?).

### CODE REVIEW

**Comment by andyarvanitis** [comment]
Hmm, I haven't seen a build problem, but let me try a clean build early tomorrow and see if I can reproduce it.

**Comment by kritzcreek** [comment]
Sounds related to https://github.com/purescript/purescript/pull/2495

**Comment by andyarvanitis** [comment]
I bet that's it, thanks @kRITZCREEK. I've cherry-picked the commit (since I don't have enough time to do a full merge from master right now), and am doing a test build now.

**Comment by andyarvanitis** [comment]
@taktoa, I've tested and pushed up the #2495 changes. However, since I haven't actually seen this in any of my build environments, would you mind trying it out and seeing if it's fixed in yours? Also, please let me know where you're building -- I typically try on a mac with both El Cap and Sierra, as well as recent Ubuntu (and lately a bit on mingw). Thanks!

**Comment by taktoa** [comment]
I usually compile with Nix (since I run NixOS). We don't yet have `language-javascript-0.6.0.9` in nixpkgs (though I'm sure the haskellPackages package set, which includes all of Hackage, albeit at slightly old versions, will be regenerated soon), so I had to manually add a package for that version to my system, but once I had done that it successfully built, so I'll close this PR.

**Comment by andyarvanitis** [comment]
Thanks!

**Pull request closed without merging**
