### PR TITLE
Nix build

### PR DESCRIPTION
**Pull request by kayhide**
This PR supports `nix build`.

The build setting is based on [haskell.nix](https://github.com/input-output-hk/haskell.nix).
Before building, it is advised to configure cachix:
https://app.cachix.org/cache/iohk

To build:

```console
$ nix build -f . psgo.components.exes.psgo
```

and you will see the executable ready at `result/bin/psgo`.

To install the executable into your nix profile:

```console
$ nix-env -f . -iA psgo.components.exes.psgo
```

Now `psgo` is available:

```console
$ psgo --help
Usage: psgo OPTIONS COREFN-FILES
  PureScript to native (via go) compiler
...
```

This PR also updates purescript version to 0.13.6.

### CODE REVIEW

**Comment by andyarvanitis** [comment]
Thanks for the PR. I'll need to run tests on 0.13.6 before merging. While I don't mind moving forward (though it generally hasn't been necessary until a major release), is there a particular reason why you did so?

**Comment by kayhide** [comment]
@andyarvanitis Hi, thanks for taking care of my PR.

Yes, I first tried the purescript version as is, but it did not work because of the lack of proper tool dep.
It should have had `happy` on `package.yaml`.
This was fixed on [this PR](https://github.com/purescript/purescript/pull/3660).

**Comment by NickHu** [comment]
Doesn't build anymore:

```
error: attribute 'nixpkgs-1903' missing, at /tmp/purescript-native/default.nix:3:16
(use '--show-trace' to show detailed location information)
```

**Comment by andyarvanitis** [comment]
I finally ran the ran the standard compiler tests and everything looks good. Thanks!

**Comment by andyarvanitis** [comment]
And sorry it took so long...

**Comment by kayhide** [comment]
No problem!
And thanks for taking care of this!

**Pull request merged**
